name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --shm-size=2g
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI tests
        env:
          DISPLAY: :99
        run: |
          pytest tests/ui --html=reports/ui_report.html --self-contained-html

      - name: Upload UI report
        uses: actions/upload-artifact@v3
        with:
          name: ui-report
          path: reports/ui_report.html

  api-tests:
    runs-on: ubuntu-latest
    needs: ui-tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: |
          pytest tests/api --html=reports/api_report.html --self-contained-html

      - name: Upload API report
        uses: actions/upload-artifact@v3
        with:
          name: api-report
          path: reports/api_report.html
